services:
  a2a-compliance-checker:
    build: .
    container_name: a2a-compliance-checker
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=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
      - OPENAI_BASE_URL=https://openrouter.ai/api/v1
    stdin_open: true
    tty: true
    networks:
      - agents-net
      - agents-db-net


networks:
  agents-net:
    external: true
  agents-db-net:
    external: true
